apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: guacamole
type: Opaque
data:
  # base64-encoded password: echo -n 'your-password' | base64
  postgresql-password: Z3VhY2Ftb2xlCg==
