apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-client
  namespace: guacamole
  labels:
    app: guacamole-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole-client
  template:
    metadata:
      labels:
        app: guacamole-client
    spec:
      initContainers:
        - name: wait-for-guacd
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z guacd.guacamole.svc.cluster.local 4822; do echo waiting for guacd; sleep 2; done;",
            ]
      containers:
        - name: guacamole
          image: guacamole/guacamole:1.6.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: REMOTE_IP_VALVE_ENABLED
              value: "true"
            - name: GUACD_HOSTNAME
              value: guacd.guacamole.svc.cluster.local
            - name: GUACD_PORT
              value: "4822"
            - name: POSTGRESQL_HOSTNAME
              value: postgresql.guacamole.svc.cluster.local
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: POSTGRESQL_DATABASE
              value: guacamole
            - name: POSTGRESQL_USER
              value: guacamole
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgresql-password

---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: guacamole
  labels:
    app: guacamole-client
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: guacamole-client
  type: ClusterIP
